### ISSUE TITLE
Always fetching the oldest tarball

### ISSUE THREAD

**Issue by ghost** [jes/collapseos-doc#2]
Hello @jes. Since the /files/ change, I've noticed that the documentation is always generated from the *oldest* tarball. I fixed it locally by adding a "g" at the regexp at grab-collapseos:23. I believe that this line never quite worked as intended because "snapshots" would always be a 1-sized array, but worked by chance because previously, the first matching link was always the good one.

**Comment by jes** [comment]
Whoops! Good catch, thanks, fixed now.
