### ISSUE TITLE
doc/asm/6502.txt: # is shown as headline

### ISSUE THREAD

**Issue by nubok** [jes/collapseos-doc#3]
In

https://incoherency.co.uk/collapseos/asm/6502.txt.html

you can read:

> Addressed opcodes take an address argument which needs to be
> filtered through address mode words.
> 
> Immediate
> <>   ZeroPage
> <X+> ZeroPage+X
> <Y+> ZeroPage+Y
> ()   Absolute
> (X+) Absolute+X
> (Y+) Absolute+Y
> [X+] Indirect+X
> []Y+ Indirect+Y

The "Immediate" should not be shown as headline, but a line starting with "#".

As a fix, I would suggest that if the line after the one starting with "#" is not empty, "#" at the beginning of a line should not be interpreted as headline marker, but as ordinary text.

**Comment by jes** [comment]
Thanks, I've fixed this now!

There was one other interesting case. The first subheading on https://incoherency.co.uk/collapseos/faq.txt.html ("What is the easiest way to run Collapse OS on a modern computer?") is split across 2 lines.

With the change as you suggested, this no longer gets turned into a heading, so the logic I went for was that a "# ..." line gets turned into a heading if the next line is blank or if the next line begins with whitespace. Then the only diff is that "# Immediate" is handled correctly, everything else remains the same.

It's done with this hairy regex: https://github.com/jes/collapseos-doc/blob/master/mk-html-doc#L137
